### ISSUE TITLE
CondaError: Run 'conda init' before 'conda activate'

### ISSUE THREAD

**Issue by M4RT1NJB** [ronaldmannak/PicoMLXServer#1]
Looks like a nice project, just not sure if I'm doing something wrong or not.
I'm also not sure if the fact that my default shell is zsh is relevant?
In the terminal I can create and activate the pico environment, and run the conda init command when necessary.

I already had (home)brew and Miniconda installed, but it seems the app is falling over when it tries to activate the pico environment during the setup: 

```
$ cd /Users/me
$ brew -v
/opt/homebrew/bin//brew
/opt/homebrew/bin//conda
/opt/homebrew/bin//brew
Homebrew 4.2.14

Ready.
$ cd /Users/me
$ conda --version
conda 24.1.2

Ready.
$ cd /Users/me
$ conda activate pico

CondaError: Run 'conda init' before 'conda activate'
```

I've also tried building in Xcode, but the same error.

Update: Tried it on another Mac, one that didn't already have conda or any mlx libraries installed, and I didn't get the conda init error message, so was able to start a server.  I'm guessing there is some difference between the environment on the machines. I will continue to investigate. The machine that it fails on has already got various mlx examples and models working including the mlx_lm http server functioning correctly.

**Comment by ronaldmannak** [comment]
@M4RT1NJB Can you check if version 0.1.1 fixes your issue?

**Comment by M4RT1NJB** [comment]
Thanks for the thorough explanation. 
Just tested 0.1.1 release and can confirm that it now completes the setup and Conda init  successfully.

The next problem is likely user error, or a different issue: 

Once the server is running I can't get any chat client to work with the API which should be the same as if running from the command line:  - odd characters in the  log?

PicoMLXServer:
`127.0.0.1 - - [21/Mar/2024 16:49:18] "[33mPOST /v1/chat/completions HTTP/1.1[0m" 404 -
`

Directly:
```
python -m mlx_lm.server --port 1234 --host 0.0.0.0 --trust-remote-code --model  mlx-community/dolphin-2.6-mistral-7b-dpo-laser-4bit-mlx
...
127.0.0.1 - - [21/Mar/2024 16:47:52] "POST /v1/chat/completions HTTP/1.1" 200 -

```

**Comment by ronaldmannak** [comment]
@M4RT1NJB can you open a new separate issue for that and add the steps needed to reproduce the issue? Thanks!
